version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    links:
     - php
     - database
    volumes:
      - ./server.conf:/etc/nginx/nginx.conf:ro
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      - ../src:/var/www/html

  php:
    build: ./php-fpm-composer
    container_name: d8_php
    ports:
      - "9000:9000"
    volumes:
      - ../src:/var/www/html

  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=aDieCHDo
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=chAKunRAif
      - MYSQL_DATABASE=drupal8
    volumes:
      - "../db:/var/lib/mysql"
    ports:
      - "3306:3306"
